<?php
$labels = [
    'name'                => _x( 'Pogosta vprašanja', 'Post Type General Name', APP_DOMAIN ),
    'singular_name'       => _x( 'Pogosto vprašanje', 'Post Type Singular Name', APP_DOMAIN ),
    'menu_name'           => __( 'Pogosta vprašanja', APP_DOMAIN ),
    'parent_item_colon'   => __( 'Parent vprašanje', APP_DOMAIN ),
    'all_items'           => __( 'Vsa pogosta vprašanja', APP_DOMAIN ),
    'view_item'           => __( 'Poglej vprašanje', APP_DOMAIN ),
    'add_new_item'        => __( 'Dodaj novo vprašanje', APP_DOMAIN ),
    'add_new'             => __( 'Dodaj novo', APP_DOMAIN ),
    'edit_item'           => __( 'Uredi', APP_DOMAIN ),
    'update_item'         => __( 'Posodobi', APP_DOMAIN ),
    'search_items'        => __( 'Išči', APP_DOMAIN ),
    'not_found'           => __( 'Ni najdenih vprašanj', APP_DOMAIN ),
    'not_found_in_trash'  => __( 'Ni najdenih vprašanj v smeteh', APP_DOMAIN ),
];
return [
    'label'               => __( 'Pogosta vprašanja', APP_DOMAIN ),
    'description'         => __( 'Pogosta vprašanja', APP_DOMAIN ),
    'labels'              => $labels,
    'supports'            => ['title', 'editor', 'revisions', 'author', 'thumbnail'],
    'taxonomies'          => [],
    'hierarchical'        => true,
    'public'              => true,
    'show_ui'             => true,
    'show_in_menu'        => true,
    'show_in_nav_menus'   => true,
    'show_in_admin_bar'   => true,
    'menu_position'       => 4,
    'menu_icon'           => 'dashicons-editor-help',
    'rewrite'             => ['slug' => 'pogosta-vprasanja', 'with_front' => false],
    'can_export'          => true,
    'has_archive'         => true,
    'exclude_from_search' => true,
    'publicly_queryable'  => true,
    'show_in_rest'        => true,
];
