<?php
$labels = [
    'name'                => _x( 'Sponzorji', 'Post Type General Name', APP_DOMAIN ),
    'singular_name'       => _x( 'Sponzor', 'Post Type Singular Name', APP_DOMAIN ),
    'menu_name'           => __( 'Sponzorji', APP_DOMAIN ),
    'parent_item_colon'   => __( 'Parent sponzor', APP_DOMAIN ),
    'all_items'           => __( 'Vsi sponzorji', APP_DOMAIN ),
    'view_item'           => __( 'Poglej sponzorja', APP_DOMAIN ),
    'add_new_item'        => __( 'Dodaj novega sponzorja', APP_DOMAIN ),
    'add_new'             => __( 'Dodaj novega', APP_DOMAIN ),
    'edit_item'           => __( 'Uredi', APP_DOMAIN ),
    'update_item'         => __( 'Posodobi', APP_DOMAIN ),
    'search_items'        => __( 'Išči', APP_DOMAIN ),
    'not_found'           => __( 'Ni najdenih sponzorjev', APP_DOMAIN ),
    'not_found_in_trash'  => __( 'Ni najdenih sponzorjev v smeteh', APP_DOMAIN ),
];
return [
    'label'               => __( 'Sponzorji', APP_DOMAIN ),
    'description'         => __( 'Sponzorji', APP_DOMAIN ),
    'labels'              => $labels,
    'supports'            => ['title', 'editor', 'revisions', 'thumbnail'],
    'taxonomies'          => [],
    'hierarchical'        => true,
    'public'              => true,
    'show_ui'             => true,
    'show_in_menu'        => true,
    'show_in_nav_menus'   => true,
    'show_in_admin_bar'   => true,
    'menu_position'       => 4,
    'menu_icon'           => 'dashicons-money-alt',
    'rewrite'             => ['slug' => 'sponzorji', 'with_front' => false],
    'can_export'          => true,
    'has_archive'         => true,
    'exclude_from_search' => true,
    'publicly_queryable'  => true,
    'show_in_rest'        => true,
    'capability_type'     => 'post',
    'capabilities'        => [
        'edit_post' => 'edit_sponzor',
        'edit_posts' => 'edit_sponzorji',
        'edit_others_posts' => 'edit_other_sponzorji',
        'publish_posts' => 'publish_splonzorji',
        'read_post' => 'read_splonzor',
        'read_private_posts' => 'read_private_sponzorji',
        'delete_post' => 'delete_sponzor'
    ]
];
